services:
  dotnetapp:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - .:/workspace
    ports:
      - "5000:5000"
    command: tail -f /dev/null
