jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['application/application.sln', 'seks-tdd/seks-tdd.sln', 'code-kata/code-kata.sln']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore ${{ matrix.project }}
    - name: Build
      run: dotnet build ${{ matrix.project }} --no-restore
    - name: Test
      run: dotnet test ${{ matrix.project }} --no-build
